### ISSUE TITLE
Installation documentation should mention hoverxref_auto_ref = True

### ISSUE THREAD

**Issue by asmeurer** [readthedocs/sphinx-hoverxref#13]
https://sphinx-hoverxref.readthedocs.io/en/latest/installation.html says:

> After installing the package and adding the extension in the conf.py file, all the :ref: roles will show a tooltip when hovering with the mouse.

But this is wrong. You have to set hoverxref_auto_ref = True for this to work. The page should mention this, since I suspect this will be desired by most. Alternately, I would suggest making True the default for this option.

**Comment by humitos** [comment]
Thanks for the feedback!

You are right. I think that page should mention the role `:hoverxref:` and pointing out to the `hoverxref_auto_ref`. I think that making the default `True` for that config is too aggressive, IMO.

**Comment by humitos** [comment]
@asmeurer I updated the docs. Let me know if they reflects the behavior in a better way: https://sphinx-hoverxref.readthedocs.io/en/latest/installation.html

**Comment by asmeurer** [comment]
I would suggest adding it to the code example, where the extensions is. That way it is more obvious. 

By the way, I tried enabling this for the SymPy docs, but it didn't seem to work. Is it supposed to work for "see also" links like these https://docs.sympy.org/latest/modules/core.html#see-also?

**Comment by humitos** [comment]
> I would suggest adding it to the code example, where the `extensions` is. That way it is more obvious.

Thanks for the suggestion! All the examples of usages are under the "Usage" page. Although, it could be good to have the simplest case mentioned in the "Installation" page.

I'm not sure yet, but I will try to add it and see how it looks like.

> By the way, I tried enabling this for the SymPy docs, but it didn't seem to work. 

Great!

> Is it supposed to work for "see also" links like these [docs.sympy.org/latest/modules/core.html#see-also](https://docs.sympy.org/latest/modules/core.html#see-also)?

Checking the [source code](https://github.com/sympy/sympy/blob/master/sympy/core/assumptions.py#L125), you are using ``.. seealso::` directive that includes ``:py:class:`` roles. To render tooltips on Sphinx Python Domain, you need to use the config `hoverxref_domains`, see https://sphinx-hoverxref.readthedocs.io/en/latest/configuration.html#confval-hoverxref_domains

Let me know if that works.

**Comment by humitos** [comment]
We talk more about this at https://github.com/sympy/sympy/issues/17456

I'm closing for now. Thanks again for the feedback.
