### ISSUE TITLE
Figure it out a good way to remove `title=` attribute on intersphinx nodes

### ISSUE THREAD

**Issue by humitos** [readthedocs/sphinx-hoverxref#133]
I originally removed the `node['reftitle']` attribute because it doesn't make sense the browser shows the default tooltip (browser's built-in) and immediately after that our tooltip was shown. This behavior is a little confusing and it's not _styled_ in my opinion. That's why I removed it.

![Screenshot_2021-06-01_16-34-21](https://user-images.githubusercontent.com/244656/120341408-23e73e00-c2f7-11eb-8c16-ec27a62c675c.png)

However, removing this attribute made other extensions break (`sphinx.ext.inheritance_diagram`) which expects that attribute exists.

I went back in [`0a75b73` (#86)](https://github.com/readthedocs/sphinx-hoverxref/pull/86/commits/0a75b73d1fd7969dc5c838fb0093e130de774dd3) and I'm opening this issue to find a better solution to avoid this.

We could:

1. define it as `node['reftitle'] = ''`
   * it makes the browser to not show the built-in tooltip
   * I'm not sure about the accessibility implication it has
   * is the HTML still valid? It will generate a `<a title="">` tag
2. use javascript to remove all the `title=` from tags with `.hoverxref .external` on document load
3. other ideas?

See https://github.com/readthedocs/sphinx-hoverxref/pull/86#issuecomment-852136211

**Comment by stsewd** [comment]
> use javascript to remove all the title= from tags with .hoverxref .external on document load

I think that's a good solution, and it also keeps a good experience for people that don't have js enabled.

**Comment by stsewd** [comment]
Also, maybe there is a way to disable/improve the default tooltip with css?

**Comment by humitos** [comment]
> use javascript to remove all the `title=` from tags with `.hoverxref .external` on document load

I found that this code works find only over our own nodes:

```javascript
$('.hoverxref').each(function () { $(this).removeAttr('title')});
```
