### ISSUE TITLE
Include jQuery as dependency

### ISSUE THREAD

**Issue by humitos** [readthedocs/sphinx-hoverxref#160]
It seems that Sphinx will remove jQuery in the future releases, see https://github.com/sphinx-doc/sphinx/issues/7405

When that happens, we will need to vendor our own jQuery version because tooltipster requires it.

**Comment by nienn** [comment]
Related issue on the theme repo: https://github.com/readthedocs/sphinx_rtd_theme/issues/1253

**Comment by humitos** [comment]
The removal will happen on 6.0: https://github.com/sphinx-doc/sphinx/issues/10070

**Comment by humitos** [comment]
This will be managed by the `sphinx-jquery` extension we plan to create in the near future. I'm removing it from my current sprint because I'm not working on it for now.
