### ISSUE TITLE
Unexpect behavior for referencing external packages

### ISSUE THREAD

**Issue by rocco8773** [readthedocs/sphinx-hoverxref#170]
Over at `plasmapy` we're trying to configure `sphinx-hoverxref` for our package (https://github.com/PlasmaPy/PlasmaPy/pull/1437).  In our documentation we liberally use `intersphinx` so we can provide link backs for our users.  In setting up `hoverxref` I've noticed it doesn't provide tooltips for all valid `sphinx` syntax.  For example, for all the following syntax `intersphinx`/`sphinx` will  generate the proper links, but `hoverxref` will only work with the last set.  For this I do have `default_role = "obj"`.

```rst
.. no tooltip generated
`astropy.units.Quantity`
`~astropy.units.Quantity`
`Quantity <astropy.units.Quantity>`

.. tooltip generated
:class:`astropy.units.Quantity`
:class:`~astropy.units.Quantity`
:class:`Quantity <astropy.units.Quantity>`
:py:class:`Quantity <astropy.units.Quantity>`
```

Is this designed behavior?  My expectation is that, if `intersphinx` can find the link, then `hoverxref` should be able to as well.

**Comment by humitos** [comment]
Thanks for opening this issue.

I think I've never tested this use case. So, I wouldn't say it's an intended behavior ☺️

I'll create a sample project to reproduce it when using a default role and check if it's possible to implement it.

**Comment by rocco8773** [comment]
That would be great! Thank you.
