### ISSUE TITLE
Python domain not working

### ISSUE THREAD

**Issue by rayzchen** [readthedocs/sphinx-hoverxref#177]
I am using `autodoc` to generate Sphinx pages but using `:py:class:` with `hoverxref_domains = ["py"]` is not working. On https://pyunity.readthedocs.io/en/feature-hoverxref/api/pyunity.audio.html the first `AudioSource` link is written as `:py:class:AudioSource` but hovering over it doesn't work.

**Comment by humitos** [comment]
Thanks for reporting this. Can you create a minimal example for us to be able to reproduce it? Thanks! 👍

**Comment by rayzchen** [comment]
Do I need to make a readthedocs project for the example as well?

**Comment by rayzchen** [comment]
https://rayzchen-testing.readthedocs.io/en/latest/
https://github.com/rayzchen/testing

**Comment by humitos** [comment]
Hi! @rayzchen were you able to find the solution? Did you close the issue for a particular reason?

**Comment by rayzchen** [comment]
One of these variables fixed it:

```python
hoverxref_intersphinx = ["python"]
hoverxref_default_type = "tooltip"
hoverxref_auto_ref = True
hoverxref_domains = [
    "py"
]
hoverxref_role_types = {
    "class": "tooltip",
    "exc": "tooltip",
    "meth": "tooltip",
    "func": "tooltip",
    "attr": "tooltip",
}
```

**Comment by humitos** [comment]
OK! Thanks for sharing the solution! 👍🏼
