### ISSUE TITLE
1.0.1: sphinx warnings `reference target not found`

### ISSUE THREAD

**Issue by kloczek** [readthedocs/sphinx-hoverxref#178]
First of all at the moment it is not possible to use straight `sphinx-build`
```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v4.5.0

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 425, in load_extension
    mod = import_module(extname)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'hoverxref'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 272, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 223, in __init__
    self.setup_extension(extension)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 380, in setup_extension
    self.registry.load_extension(self, extname)
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 428, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname,
sphinx.errors.ExtensionError: Could not import extension hoverxref.extension (exception: No module named 'hoverxref')

Extension error:
Could not import extension hoverxref.extension (exception: No module named 'hoverxref')
```
This could be fixed by patch like below
```patch
--- a/docs/conf.py~     2022-04-28 10:47:51.000000000 +0000
+++ b/docs/conf.py      2022-04-28 10:48:25.330328346 +0000
@@ -14,8 +14,8 @@
 #
 import os
 import datetime
-# import sys
-# sys.path.insert(0, os.path.abspath('.'))
+import sys
+sys.path.insert(0, os.path.abspath('..'))


 # -- Project information -----------------------------------------------------
```
That patch just uncomments already present lines taken from sphinx example and adds proper path.

Than .. on building my packages I'm using `sphinx-build` command with `-n` switch which shows warmings about missing references. These are not critical issues.
Here is the output with warnings:
```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v4.5.0
making output directory... done
checking bibtex cache... out of date
parsing bibtex file /home/tkloczko/rpmbuild/BUILD/sphinx-hoverxref-1.0.1/docs/refs.bib... parsed 1 entries
loading intersphinx inventory from https://docs.readthedocs.io/en/stable/objects.inv...
loading intersphinx inventory from https://www.sphinx-doc.org/en/master/objects.inv...
loading intersphinx inventory from https://docs.sympy.org/latest/objects.inv...
loading intersphinx inventory from https://numpy.org/doc/stable/objects.inv...
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 8 added, 0 changed, 0 removed
reading sources... [100%] usage
/home/tkloczko/rpmbuild/BUILD/sphinx-hoverxref-1.0.1/docs/index.rst:92: WARNING: toctree contains reference to nonexisting document 'autoapi/hoverxref/index'
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... sphinx-hoverxref.3 { installation usage configuration development releasing } /home/tkloczko/rpmbuild/BUILD/sphinx-hoverxref-1.0.1/docs/usage.rst:109: WARNING: py:class reference target not found: hoverxref.domains.HoverXRefStandardDomainMixin
done
build succeeded, 2 warnings.
```

**Comment by humitos** [comment]
Hi @kloczek! It seems that you are not installing the required dependencies.

>  Could not import extension hoverxref.extension (exception: No module named 'hoverxref')

This is because `sphinx-hoverxref` is not properly installed in the Python environment used when building the documentation.

> /home/tkloczko/rpmbuild/BUILD/sphinx-hoverxref-1.0.1/docs/index.rst:92: WARNING: toctree contains reference to nonexisting document 'autoapi/hoverxref/index'

This is because `sphinx-autoapi` is not installed in the Python environment either.

----

Let me know if that helps to debug this issue in your side. Thanks!

**Comment by kloczek** [comment]
> This is because `sphinx-hoverxref` is not properly installed in the Python environment used when building the documentation.

If you will look outside python domain you will find that literally none of the projects requires first build and install it to be able build documentation.
That patch not only allows build documentation without installing module. It guarantees as well that documentation will be build out of what is in source tree and not what is installed.
More .. if you will look on the sphinx documentation on example conf.py file https://www.sphinx-doc.org/en/master/usage/configuration.html#example-of-configuration-file you can find that such solution is in the commented part of that example.
Currently in tox.ini you have `docs` testenv to archive the same. Assembly tox venv takes time. That patch allows build documentation way simpler way .. instantly.
Try to think about KISS principle 😋 

Some stats from my rpm packages spec files
```consile
[tkloczko@devel-g2v SPECS]$ grep "%{name}-add_module_path_in_conf.py.patch" python-* | wc -l; grep %sphinx_build_man python-* | wc -l
102
423
```
So .. above means that less 1/4 of all my packages with python modules which builds documentation using sphinx requires patch like I've dropped above. Every other modules already have that kind of `sys.path` tweak.
That first number already is going down as I've started +2 months ago submitting similar fixes against all other modules which I've packaged.

Really .. please try that patch and try use straight sphinx-build command.
Using for that tox is nothing more than overkill.

**Comment by humitos** [comment]
I understand the case and I can uncomment those lines. However, even uncommenting them, how are you going to build the documentation without installing all the other dependencies listed in `docs/requirements.in`?

**Comment by kloczek** [comment]
> I understand the case and I can uncomment those lines. However, even uncommenting them, how are you going to build the documentation without installing all the other dependencies listed in `docs/requirements.in`?

Don't worry about that. That output is from packaging build log.
All necessary build requirements necessary to build module, build documentation install and test module have been installed in that particular case.
```console
[tkloczko@devel-g2v SPECS]$ grep BuildRequires python-sphinx-hoverxref.spec
BuildRequires:  python3dist(build)
BuildRequires:  python3dist(pip)
BuildRequires:  python3dist(setuptools)
BuildRequires:  python3dist(sphinx)
BuildRequires:  python3dist(sphinxcontrib-bibtex)
BuildRequires:  python3dist(sphinx-prompt)
BuildRequires:  python3dist(sphinx-tabs)
BuildRequires:  python3dist(wheel)
BuildRequires:  python3dist(pytest)
```
