### ISSUE TITLE
Hoverxref still not working on Jupyter Book?

### ISSUE THREAD

**Issue by mscharling** [readthedocs/sphinx-hoverxref#180]
Hi there,

I'm currently trying to implement sphinx-hoverxref in my Jupyter Book and I can't make it work. I'm aware of the relatively new version of Jupyter Book working with RTD theme and that makes me wonder why it won't work. So, have I missed something or does sphinx-hoverxref not work with Jupyter Book?

**Comment by humitos** [comment]
Hi @mscharling! I'm not a user of Jupyter Book. Can you explain to me why it doesn't work? What error gives you or what's the problem you are having? Thanks!

**Comment by mscharling** [comment]
Sure, I thought it was unnecessary to put in if it was known to be unsupported. But.. I'm mostly interested in the `{term}` part of hoverxref:

In my _config.yml I have added:
```
sphinx:
  ...
  extra_extensions:
    - hoverxref.extension
```

In my Jupyter Book-folder and in the hoverxref-folder I have created conf.py with
```
hoverxref_roles = [
    'term',
]
```

I have a glossary.md with
```{glossary}
example
   and a lot of text to explain the example.
```

And lastly I then call "[...] {term}´example´ [...]" in my text markdown file. 

When I hover "example" nothing shows and I don't get any errors when building my book. It runs normally and I get the usual `{term}` click-functionality of the linking to the ref in my glossary.md file.

**Comment by humitos** [comment]
> In my Jupyter Book-folder and in the hoverxref-folder I have created conf.py with

Shouldn't this config be in the `_config.yml` when using Jupyter Book? See https://jupyterbook.org/en/latest/advanced/sphinx.html#manual-sphinx-configuration

I don't think you have to use a `conf.py` when using Jupyter Book.

**Comment by mscharling** [comment]
> Shouldn't this config be in the `_config.yml` when using Jupyter Book? See https://jupyterbook.org/en/latest/advanced/sphinx.html#manual-sphinx-configuration

**Comment by mscharling** [comment]
**Sorry, I posted the comment as closing comment.** Can we reopen the issue?

**Comment by mscharling** [comment]
**Misclicked..** 😅

**Comment by humitos** [comment]
> Now I get the following error when building my book:
> 
> "Using default style (tooltip) for unknown typ (term). Define it in hoverxref_role_types."

This is not an error, just an info message. That's fine. If you want to remove that message, you can specify which tooltip type it should be used for `term`: https://sphinx-hoverxref.readthedocs.io/en/latest/configuration.html#confval-hoverxref_role_types

> The book is still builded but removes the "example" from `{term}´example´`. When I look into `domains.py` for hoverxref I don't see anything missing. What could it then be?

I'm not sure. This could be a problem on Jupyter Book, maybe? I haven't seen this issue when using Sphinx directly.

Also, can you share the repository to your docs, or a basic example of how I can get the same behavior so I can test it by myself? Another option could be to ask in the Jupyter Book issue tracker itself, since I'm not sure this is a problem on hoverxref itself.

**Comment by mscharling** [comment]
> Also, can you share the repository to your docs, or a basic example of how I can get the same behavior so I can test it by myself? Another option could be to ask in the Jupyter Book issue tracker itself, since I'm not sure this is a problem on hoverxref itself.

Sure. I've created the repository with some example code [here](https://github.com/mscharling/hoverxrefandjb). Thank you for taking your time to investigate this.

**Comment by humitos** [comment]
> I've created the repository with some example code [here](https://github.com/mscharling/hoverxrefandjb).

I'm not sure to follow your example code. There is only one file there `README.md`. Maybe you forgot to push some changes?

> hoverxref_roles: term

Also, this should be a list (see https://sphinx-hoverxref.readthedocs.io/en/latest/configuration.html#confval-hoverxref_roles). So I think you need something like:

```yaml
sphinx:
  config:
    ...
    hoverxref_roles:
      - term
```

**Comment by humitos** [comment]
I found the issue.

Steps to reproduce it:

1. Create the book and install dependencies
```
fades -d jupyter-book -d sphinx-hoverxref -d matplotlib -x jupyter-book create mynewbook/
```
1. Edit the YAML to setup hoverxref
```yaml
# _config.yml

sphinx:
  config:
    hoverxref_roles:
      - term
    hoverxref_role_types:
      term: modal
  extra_extensions:
    - hoverxref.extension
```
1. Edit `mynewbook/intro.md` to add:
```
```{glossary}
Term one
  An indented explanation of term 1
```

Here is my term!

{term}`Term one`

Is it shown here?
```
1. Build the book
```
fades -d jupyter-book -d sphinx-hoverxref -d matplotlib -x jupyter-book build mynewbook/
```

When you open `mynewbook/_build/html/index.html` you will see that the `Term one` is not shown. However, if you inspect the DOM, the HTML element _is_ there. It seems there is a problem with CSS where Jupyter Book's theme interferes with the `.tooltip` (`opacity: 0`) and `.modal` (`display: none`) classes making them invisible.

![Screenshot_2022-05-30_16-22-35](https://user-images.githubusercontent.com/244656/171012026-1a53e5b4-3d18-4f0a-a7c2-6f4a5afbd483.png)


@choldgraf @chrisjsewell do you know where those CSS classes come from?

**Comment by choldgraf** [comment]
Hmmm good question, either bootstrap or it's in the theme css itself. I suspect it's the latter because I'm guessing you tested this extension with bootstrap already. Want to open an issue in the book theme?

**Comment by humitos** [comment]
Thanks @choldgraf. I opened https://github.com/executablebooks/sphinx-book-theme/issues/577

@mscharling feel free to subscribe there as well, in case you want to follow up the news about this issue.

**Comment by humitos** [comment]
Hi @mscharling! Would you like to try installing sphinx-hoverxref from #205 with your project and let me know if it works as you expected?

**Comment by humitos** [comment]
Hi @mscharling! I just deployed a new version of this extension: `1.1.2`. Please, give it a try and let me know if this makes it work properly on your Jupyter Book project. I hope it does! 👍🏼

**Comment by mscharling** [comment]
Hi @humitos, sorry for the late respons. Lots of time has gone without me working on my project... Howver, nice to see that this is now possible for Jupyter Books. My project is currently not using RTD and from [#278 ](https://github.com/readthedocs/sphinx-hoverxref/issues/278) I guess I will have to wait checking whether this works for my project or not. Thank you for your time on this :)
