### ISSUE TITLE
New tooltip style suggestion

### ISSUE THREAD

**Issue by MariannaKononenko** [readthedocs/sphinx-hoverxref#22]
Would be great to have such kind of tooltips as on this page:
https://help.apple.com/xcode/mac/current/#/dev84c38774c
![image](https://user-images.githubusercontent.com/48750990/64919167-de43b400-d7a7-11e9-900e-8af550224aff.png)

**Comment by humitos** [comment]
Thanks for the suggestion!

I just found this JS library that could be good to include as a second option (via a setting) instead of using the current ones.

**Comment by humitos** [comment]
This is another that could be interesting also, https://github.com/kylefox/jquery-modal and looks simpler to implement.
