### ISSUE TITLE
Help with packaging `sphinx-hoverxref` for `conda-forge`

### ISSUE THREAD

**Issue by BSGalvan** [readthedocs/sphinx-hoverxref#237]
Hello!

I am currently in the process of submitting a recipe to `conda-forge` for getting `sphinx-hoverxref`.

~Seeing as how this package is currently in beta~ Even though the package is now stable, it would be wonderful if any of the package devs could accept to be a fellow maintainer of the `conda-forge` recipe. This would help keep the recipe (and consequently `conda-forge` builds) fresh.

You can see the (draft) PR, [here](https://github.com/conda-forge/staged-recipes/pull/20748).

Thanks in advance and cheers!

**Comment by humitos** [comment]
Hi @BSGalvan! Thanks for opening this issue.

Why do you say this package is in beta? Have you read this somewhere in our documentation? Or do you refer that the conda-forge recipe is in beta?

In any case, this package is not in beta anymore and we have release the version 1.x some time ago. If we are saying we are in beta in some place, please point us out there and we will change it.

**Comment by BSGalvan** [comment]
Ah my bad, I didn't see the 1.x badge here on GitHub!

The [pypi.org page](https://pypi.org/project/sphinx-hoverxref/) warns of the package being in beta, which is where I picked up the misconception. My apologies!

**Comment by BSGalvan** [comment]
@humitos

For the recipe, I will need to specify a minimum python version with which `sphinx-hoverxref` will be compatible.

From my cursory glance at `tox.ini`, it seems that testing happens down to python 3.8.
Would it be correct if I set a dependency of python >= 3.8, or is there another constraint somewhere else that I've missed?

**Comment by humitos** [comment]
> Would it be correct if I set a dependency of python >= 3.8, or is there another constraint somewhere else that I've missed?

That would be fine, yeah.

**Comment by BSGalvan** [comment]
The recipe has successfully passed CI checks, and it ready to be put on `conda-forge`!

@humitos, before I publish the PR, would it be okay if I add you to the [list of maintainers here](https://github.com/conda-forge/staged-recipes/pull/20748/files#diff-3b9b9f0d29fd6ad27cdb6d32076668c838e9910bcd6156e8d3a1893e76f357d3R47)?

**Comment by humitos** [comment]
I don't have experience with conda-forge, so I don't think I'll be useful there

**Comment by humitos** [comment]
I don't have experience with conda-forge, so I don't think I'll be useful there

**Comment by BSGalvan** [comment]
No worries, then!

I will mark the PR ready for now.
In the future if any of the maintainers here want to hop on, I should be able to add them in following [instructions here](https://conda-forge.org/docs/maintainer/updating_pkgs.html#updating-the-maintainer-list) (note to self).

Let me know if that is alright, and thank you for your time!

**Comment by humitos** [comment]
Thanks for doing this work and supporting this extension. I understand there is no more work required in this issue, so I'll close it
