### ISSUE TITLE
Start a stand alone JS package for hoverxref

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/sphinx-hoverxref#245]
Before the end of the year, we'd like to prioritize allowing hoverxref to be used outside Sphinx. I'll have a particular amount of front end scaffolding to bring in to facilitate that, and there will be some changes to patterns here.

Noting this for now so it's on our roadmap. @humitos we should chat before I get into planning here.

**Comment by humitos** [comment]
We have started this work as part of the new js client at https://github.com/readthedocs/readthedocs-client/. However, we think we are not able to prioritize this work before next year probably.

**Comment by ericholscher** [comment]
Should we close this issue, and just assume it's already being tracked in the client work?

**Comment by humitos** [comment]
Yes. I think all the work/time should be put there 👍
