### ISSUE TITLE
Internal References not displaying on Hidden builds.

### ISSUE THREAD

**Issue by EvieePy** [readthedocs/sphinx-hoverxref#263]
Howdy!

Thought I might bring this up (not sure if it is a known quirk).
But if you have an active build on RTD but it is set to `Hidden` under: 
`https://readthedocs.org/dashboard/<project>/version/<project-version>/edit/ `

- Internal references will not display tooltips/modals.
- Intersphinx works correctly.

It might be useful if this is by design or unavoidable to add a warning to the docs.
Thanks

**Comment by humitos** [comment]
Thanks for reporting this. Do you have project hitting this issue? What is the URL of the page and the specific link that should show the tooltip but it's not? That would be useful to debug this.

**Comment by EvieePy** [comment]
Seems to not be happening now when I switch the branch back to hidden. Though I can confirm it wasn't a cache setting or other setting as I had been disabling cache and it wasn't until I turned a branch off Hidden that it worked.

I will note that when I did switch the branch from Hidden to not, the site (for that specific version) went down and was inaccessible for around 30 seconds.

I will try reproducing this following the steps I took previous.

**Comment by EvieePy** [comment]
Creating a new branch doesn't seem to invoke this issue either so I am wondering whether this was a slight mishap in the readthedocs stack.

It was stange to me that the site failed when I switched it off Hidden so I am not sure if that helps.

It was also strange to me that Intersphinx docs were correctly working.


https://github.com/readthedocs/sphinx-hoverxref/assets/29671945/1d9c5404-65ec-4b3c-83d3-8b3010f07ca8

**Comment by humitos** [comment]
Thanks! Please, if you find a way to reproduce the issue, keep us posted here so we can debug it and confirm/fix it.
