### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by humitos** [readthedocs/sphinx-hoverxref#306]
It will include:

- https://github.com/readthedocs/sphinx-hoverxref/pull/302
- Some package updates

**Comment by humitos** [comment]
@chrizzFTD I plan to make a release next week 👍🏼

**Comment by humitos** [comment]
I just released 1.4.1, https://pypi.org/project/sphinx-hoverxref/

@chrizzFTD please, give it a try and let me know if it works as expected 👍🏼

**Comment by chrizzFTD** [comment]
Thanks a lot, @humitos! I can confirm the new release [works as expected](https://grill--41.org.readthedocs.build/en/41/api.html#grill.cook.UsdAsset) from [my latest buid](https://readthedocs.org/projects/grill/builds/25625372/) using 1.4.1:
> Collecting sphinx-hoverxref>=1.4.1 (from grill==0.17.0)
  Downloading sphinx_hoverxref-1.4.1-py2.py3-none-any.whl.metadata (3.0 kB)
😃
