### ISSUE TITLE
DeprecationWarning with Sphinx v8.0.2

### ISSUE THREAD

**Issue by Zac-HD** [readthedocs/sphinx-hoverxref#312]
```
.../python3.10/site-packages/hoverxref/extension.py:312: RemovedInSphinx90Warning: The '_Opt' object tuple interface is deprecated, use attribute access instead for 'default', 'rebuild', and 'valid_types'.
  default, rebuild, types = app.config.values.get('hoverxref_tooltip_api_host')
.../python3.10/site-packages/hoverxref/extension.py:280: RemovedInSphinx90Warning: The '_Opt' object tuple interface is deprecated, use attribute access instead for 'default', 'rebuild', and 'valid_types'.
  default, rebuild, types = app.config.values.get('hoverxref_modal_class')
.../python3.10/site-packages/hoverxref/extension.py:67: RemovedInSphinx90Warning: The '_Opt' object tuple interface is deprecated, use attribute access instead for 'default', 'rebuild', and 'valid_types'.
  context[attr] = app.config.values[attr][0]
```

found via [this CI run](https://github.com/HypothesisWorks/hypothesis/actions/runs/11226199428/job/31206275266?pr=4129#step:6:713) on https://github.com/HypothesisWorks/hypothesis/pull/4129, where we continue to be very happy that hoverxref exists 💖

**Comment by Zac-HD** [comment]
Hi Manuel, I've opened #313 to fix this issue 🙂

**Comment by jakkdl** [comment]
Would it be possible to push a small patch release with this fix? :)

**Comment by humitos** [comment]
@jakkdl this extension is deprecated now since the feature was introduced in Read the Docs application itself. It's now called links preview: https://docs.readthedocs.com/platform/stable/link-previews.html

**Comment by edgarrmondragon** [comment]
> [@jakkdl](https://github.com/jakkdl) this extension is deprecated now since the feature was introduced in Read the Docs application itself. It's now called links preview: https://docs.readthedocs.com/platform/stable/link-previews.html

Should a warning be added to the readme in this repo, as well as a link to those docs and/or https://github.com/readthedocs/addons?

**Comment by humitos** [comment]
> Should a warning be added to the readme in this repo, as well as a link to those docs and/or [readthedocs/addons](https://github.com/readthedocs/addons?rgh-link-date=2025-04-03T18%3A40%3A37.000Z)?

Yes. I just haven't had the time to do it. Would you want to open a PR with this?

**Comment by agriyakhetarpal** [comment]
> > Should a warning be added to the readme in this repo, as well as a link to those docs and/or [readthedocs/addons](https://github.com/readthedocs/addons?rgh-link-date=2025-04-07T14%3A59%3A24.000Z)?
> 
> Yes. I just haven't had the time to do it. Would you want to open a PR with this?

I've put together a PR to mark the extension as deprecated: https://github.com/readthedocs/sphinx-hoverxref/pull/337
