### ISSUE TITLE
Errors when trying to "make html"

### ISSUE THREAD

**Issue by xding78** [readthedocs/sphinx-hoverxref#34]
I receive this error when try to "make html"

Extension error:
Could not import extension hoverxref.extension (exception: No module named 'hoverxref')
make: *** [html] Error 2

Where should the "hoverxref" folder be? should it be a sibling or child of the "docs" folder?

Thanks a lot!

**Comment by stsewd** [comment]
You need to install the extension

```
pip install sphinx-hoverxref
```
