### ISSUE TITLE
Formatting of tooltip contents?

### ISSUE THREAD

**Issue by kerimoyle** [readthedocs/sphinx-hoverxref#38]
First of all, thanks for a great extension :) It's really useful.  I'm having trouble with the formatting of the popup - please see shots below.  

1) Whenever we have a table included in the popup, its columns get wrapped (which is nice), but the linespacing is messed up?
![image](https://user-images.githubusercontent.com/46887220/78091484-76924500-7429-11ea-90e5-47d8779d3a9b.png)

2) Is there a way to format the heading so it remains the same (or larger?) than the tooltip contents? In the image below the link text "A CellML identifier:" is smaller than the other points?  Neither have any special formatting.
![image](https://user-images.githubusercontent.com/46887220/78091621-e56f9e00-7429-11ea-94e1-f530d7c8086e.png)

Thanks in advance for any thoughts - I'm not sure whether these are bugs or whether I've done something wrong somewhere!

**Comment by humitos** [comment]
> First of all, thanks for a great extension :) It's really useful.

:kissing_heart: 

I have some questions, which will help me to debug it better:

1. What theme are you using?
1. What's your documentation URL?

Currently, there is no configuration implemented at hoverxref extension level to change this. You can only change the theme of the tooltip with https://sphinx-hoverxref.readthedocs.io/en/latest/configuration.html#confval-hoverxref_tooltip_theme

If you want just to change a small CSS entries, you can take a look at the rules this extension is using: https://github.com/readthedocs/sphinx-hoverxref/blob/master/hoverxref/_static/css/tooltipster.custom.css and write your owns overriding the ones you want.

Then you can add those overrides to your project, using https://docs.readthedocs.io/en/stable/guides/adding-custom-css.html
This extension uses https://iamceege.github.io/tooltipster/. So, you can read their guide to create a custom theme at in case you want to change all the look and feel of the tooltip: https://iamceege.github.io/tooltipster/#styling

Please, let me know if this helps.

**Comment by humitos** [comment]
If you write some CSS rules that you think will be useful for other projects as well, feel free to open a PR here with these improvements.

**Comment by kerimoyle** [comment]
Thanks - I think that will help.  I'll have a look next week and see if I can answer your questions/submit some fixes :)

**Comment by kerimoyle** [comment]
OK, thanks.  I think the standard hover-popup is closer to what we're after rather than the full on modal.  I'll be doing some digging in the next couple of days and will let you know :)

**Comment by humitos** [comment]
I'm closing this issue since I think there is anything actionable from our side. Please, feel free to re-open if you consider we need to do something here.
