### ISSUE TITLE
Typlog theme seems to be not compatible

### ISSUE THREAD

**Issue by humitos** [readthedocs/sphinx-hoverxref#56]
```
Theme error:
An error happened in rendering the page 404.
Reason: UndefinedError("'metatags' is undefined")
```

Theme URL: https://sphinx-typlog-theme.readthedocs.io/

**Comment by aisk** [comment]
Got the same error, just avoid this by removing `'sphinx.ext.viewcode'` extension.

**Comment by humitos** [comment]
This seems to not be an issue anymore

![Screenshot_2020-08-31_15-29-31](https://user-images.githubusercontent.com/244656/91725321-db032d00-eb9e-11ea-9d65-2c1c6a054f24.png)

Live example: https://returns.readthedocs.io/en/latest/pages/container.html#needs-transformation

**Comment by nchelaru** [comment]
I am having the same problem, how did you resolve it?

**Comment by humitos** [comment]
Hi @nchelaru. I didn't really change anything, it just disappeared, and I assume that it was a problem in the theme itself. Are you experimenting the same issue? Could you please provide more information? What versions of sphinx, typlog, hoverxref are you using?

Do you have a project on Read the Docs where this issue is happening? Can you paste the URL of that project here?

**Comment by nchelaru** [comment]
Oh shoot, I just realized that this is an issue with the Typlog theme, rather than hoverxref. Sorry for the trouble!

Thank you for your quick reply!

**Comment by chrizzFTD** [comment]
Hi @humitos, just in case someone comes across this as well, it happened to me while working on https://github.com/thegrill/grill/pull/23, I realized this was happening when the docs environment had `jinja2-3.0.1`.

Failing docs had this log:
```bash
Collecting Jinja2>=2.3
  Downloading Jinja2-3.0.1-py3-none-any.whl
```
However, I locally had `jinja2==2.11.2` and it all worked.

I gave it a try and [locking my docs requirements](https://github.com/thegrill/grill/pull/23/commits/ee70899401cb36187dd2d45504bb81806f4a82f6) to `jinja2==2.11.2` fixes the issue for me. I didn't look deeper after that.

I have commented this as well on the `typlog` theme: https://github.com/typlog/sphinx-typlog-theme/issues/22

**Comment by humitos** [comment]
@chrizzFTD thanks for your comment here! Hopefully, it helps other people to workaround the problem.
