### ISSUE TITLE
Add glossery/term support.

### ISSUE THREAD

**Issue by Daltz333** [readthedocs/sphinx-hoverxref#57]
This would be incredibly useful for this kind of situation.

**Comment by humitos** [comment]
Hi! Thanks for the suggestion.

If you are talking about https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#glossary, I'd say that this is already supported.

You can just add `'term'` to [`hoverxref_roles`](https://sphinx-hoverxref.readthedocs.io/en/latest/configuration.html#confval-hoverxref_roles) and it just should do the magic.

Although, I just realized that the content returned by the backend is not accurate. It includes the whole glossary and not only the term definition itself.

![screenshot-sphinx-hoverxref readthedocs io-2020 04 12-04_53_23](https://user-images.githubusercontent.com/244656/79059382-98859600-7c79-11ea-9970-0abb72f56941.png)

I will try to take a look and see if I can fix this!

**Comment by humitos** [comment]
I found the issue an opened a PR that will fix it. It will render as,

![Screenshot_2020-04-12_05-21-48](https://user-images.githubusercontent.com/244656/79059720-a6d5b100-7c7d-11ea-9d9b-06ba964aff02.png)

It hopefully will be merged and deployed next week.

Thanks!

**Comment by Daltz333** [comment]
I was actually! Thank you for a quick and speedy implementation.

**Comment by humitos** [comment]
We deploy the fix today and it's already working. I'm closing this issue now. Please, let me know if it does work in your project as well.
