### ISSUE TITLE
Clarify Read the Docs configs

### ISSUE THREAD

**Issue by humitos** [readthedocs/sphinx-hoverxref#59]
I just realized that these three configs (`hoverxref_project`, `hoverxref_version` and `hoverxref_api_host`) are confusing for users, and we should probably add a note that they should not be modified.

https://sphinx-hoverxref.readthedocs.io/en/latest/configuration.html#confval-hoverxref_api_host

People is modifying them because their CI starts failing saying they are not defined and they have fail on warnings enabled. So, defining them makes the CI happy but breaks all the tooltips on RTD.

It may be good to explain this case and suggest the users to define the environment variables `READTHEDOCS_PROJECT` and `READTHEDOCS_VERSION` in their CI to avoid it failing in case they are using `-W`.

Reference: https://github.com/scrapy/scrapy/pull/4480#discussion_r409026912

**Comment by humitos** [comment]
We are showing this warning message:

```
WARNING: hoverxref extension is not fully configured. Set hoverxref_project and hoverxref_version in your conf.py file.
```

That's probably wrong, and should explain more the situation.

**Comment by ericholscher** [comment]
I'm 👍 on moving this to an `INFO`, as it will break CI builds if not.
