### ISSUE TITLE
Anyway to support tooltips for internal references created by numref?

### ISSUE THREAD

**Issue by kerimoyle** [readthedocs/sphinx-hoverxref#70]
Thanks for a great wee tool :) 

I'm having trouble combining the `numref` role with tooltips - does it perhaps need another round of rendering in the same way that mathjax panels do?  My conf.py file looks like this:
```
hoverxref_auto_ref = True
hoverxref_roles = ['ref', 'numref']
hoverxref_role_types = {
    'ref': 'tooltip',       
    'numref': 'tooltip',    
}
```
The pages are working fine for things which use the `ref` role, just not the `numref` one.  

Readthedocs site is here: https://cellml-specification-dev.readthedocs.io/en/i314_numref_hoverxref/reference/formal_and_informative/specB09.html

If you have any suggestions I'd be very glad to hear them.  Thanks!

**Comment by humitos** [comment]
Hi @kerimoyle! `:numref:` is not supported yet.

I think it won't be complicated to support it. We need to override the method [`_resolve_numref_xref`](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/domains/std.py#L815) in our Mixin for the `std` Domain.

Note to myself for the reference, the source code of that page is at https://github.com/kerimoyle/cellml-specification/blob/i314_numref_hoverxref/src/reference/sectionB_elements.inc#L293

**Comment by humitos** [comment]
Hey @kerimoyle! Would you like to test the branch from #71 in your project? I think that should add support for `:numref:`. Let me know if it does work. Thanks!

**Comment by kerimoyle** [comment]
Hi @humitos! Thanks for the quick response :) I've had a go (same page as before) but we seem to get the same behaviour ... the output from the build is [here](https://readthedocs.org/api/v2/build/10877130.txt).  Do I need to do anything different in my code to get it to work?

**Comment by humitos** [comment]
You have this line commented out

```python
# hoverxref_roles = ['ref', 'numref']
```

You need,

```python
hoverxref_roles = ['numref']
```

Let me know if that makes the difference.

**Comment by kerimoyle** [comment]
Fantastic!  Yes, that's done it :) Thanks very much!
