### ISSUE TITLE
Issue with hover content not showing up

### ISSUE THREAD

**Issue by Daltz333** [readthedocs/sphinx-hoverxref#73]
https://daltz-private.readthedocs.io/en/glossary/docs/software/advanced-controls/introduction/introduction-to-pid.html

with the relative conf.py here
https://github.com/Daltz333/frc-docs/blob/glossary/source/conf.py

**Comment by humitos** [comment]
Are you using `:hoverxref:` role?

If not, you may need to take a look at the list of configurations https://sphinx-hoverxref.readthedocs.io/en/dirhtml/configuration/ and probably enable [`hoverxref_auto_ref`](https://sphinx-hoverxref.readthedocs.io/en/dirhtml/configuration/#confval-hoverxref_auto_ref)

Let me know if that helps.

**Comment by Daltz333** [comment]
Whoops, completely forgot about that. Thanks!

**Comment by Daltz333** [comment]
Glossary preview is still not working.

**Comment by Daltz333** [comment]
I'm not using hoverx_roles and still having issues. https://github.com/Daltz333/frc-docs/blob/glossary/source/conf.py
