### ISSUE TITLE
Glossary terms in hover content lead to 404

### ISSUE THREAD

**Issue by Daltz333** [readthedocs/sphinx-hoverxref#75]
![image](https://user-images.githubusercontent.com/10674555/82108199-d18eab80-96fa-11ea-8e19-9b337e4dc992.png)

https://daltz-private.readthedocs.io/en/glossary/docs/software/advanced-controls/introduction/introduction-to-pid.html

**Comment by humitos** [comment]
@Daltz333 could you provide a working link? The one provided gives me 404.

**Comment by Daltz333** [comment]
https://daltz-private.readthedocs.io/fr/glossary/docs/software/advanced-controls/introduction/introduction-to-pid.html

**Comment by Daltz333** [comment]
And https://docs.wpilib.org/en/latest/docs/software/advanced-controls/introduction/introduction-to-pid.html

**Comment by humitos** [comment]
> [daltz-private.readthedocs.io/fr/glossary/docs/software/advanced-controls/introduction/introduction-to-pid.html](https://daltz-private.readthedocs.io/fr/glossary/docs/software/advanced-controls/introduction/introduction-to-pid.html)

This one works fine to me.

> And [docs.wpilib.org/en/latest/docs/software/advanced-controls/introduction/introduction-to-pid.html](https://docs.wpilib.org/en/latest/docs/software/advanced-controls/introduction/introduction-to-pid.html)

This one seems to be missing the `.html` part of all the links.

What's the difference in configuration on those projects?

**Comment by Daltz333** [comment]
One is set to french, the other is not. Same project. See https://github.com/wpilibsuite/frc-docs and https://github.com/wpilibsuite/frc-docs-translations

Our language versions point toward the latter, English is on the main repo. This allows us to fully automated translations, without bloating the main repo.

**Comment by Zac-HD** [comment]
If I hover over ```data``` in https://hypothesis--2467.org.readthedocs.build/en/2467/data.html#composite-strategies then the link [the rest of the documentation](https://hypothesis--2467.org.readthedocs.build/en/2467/data#interactive-draw) leads to a 404 because the `.html` is missing from `data`.

(via https://github.com/HypothesisWorks/hypothesis/pull/2467#pullrequestreview-434421684)

Not sure if that will help, but it's at least another data point!

**Comment by stsewd** [comment]
The server side of the embed app is now open source https://github.com/readthedocs/readthedocs.org/tree/master/readthedocs/embed I was trying to find an example to write tests for citations... and got rickrolled :D

https://daltz-private.readthedocs.io/

**Comment by Daltz333** [comment]
Lol, I took down my personal site, because it confused members of my organization. 

Here is a good example
frc-docs.readthedocs.io/en/glossary/docs/software/advanced-controls/introduction/introduction-to-pid.html
