### ISSUE TITLE
Broken on PR builds

### ISSUE THREAD

**Issue by Daltz333** [readthedocs/sphinx-hoverxref#76]
Currently hover content just shows the following image on PR builds.

Offender: https://frc-docs--674.org.readthedocs.build/en/674/docs/software/advanced-controls/introduction/introduction-to-pid.html

![image](https://user-images.githubusercontent.com/10674555/82130747-27fff680-979c-11ea-8e35-5a917b72ec2b.png)

**Comment by Daltz333** [comment]
Here's script output
```
Data: {"project":"frc-docs","version":674,"doc":"docs/software/advanced-controls/introduction/controls-glossary","docpath":"/docs/software/advanced-controls/introduction/controls-glossary.html","section":"term-setpoint"} hoverxref.js:66:13
URL: https://readthedocs.org/api/v2/embed/?project=frc-docs&version=674&doc=docs%2Fsoftware%2Fadvanced-controls%2Fintroduction%2Fcontrols-glossary&docpath=%2Fdocs%2Fsoftware%2Fadvanced-controls%2Fintroduction%2Fcontrols-glossary.html&section=term-setpoint hoverxref.js:68:13
```

**Comment by humitos** [comment]
Thanks for reporting. This is a known issue. We are working to fix it.

**Comment by Zac-HD** [comment]
Possibly related, we're getting broken links in the tooltips: 

> Also I don't know if this is a config problem or a bug in the plugin but links in crossrefs seem broken. If I hover over ```data``` in https://hypothesis--2467.org.readthedocs.build/en/2467/data.html#composite-strategies then the link [the rest of the documentation](https://hypothesis--2467.org.readthedocs.build/en/2467/data#interactive-draw) leads to a 404 because the `.html` is missing from `data`.

(via https://github.com/HypothesisWorks/hypothesis/pull/2467#pullrequestreview-434421684)

**Comment by Daltz333** [comment]
@Zac-HD An issue for that is already open, see #75

**Comment by humitos** [comment]
This issue is already fixed. The extension should work fine on PRs. I'm going to closing this one now and focus on #75. Thanks!
