### ISSUE TITLE
Build failed in readthedocs

### ISSUE THREAD

**Issue by devamchakrabarty** [readthedocs/sphinx-hoverxref#77]
Hi,
We can successfully install and build our project using this extension locally (make html). But when we push the code to GitHub, it triggers an automatic build in readthedocs (webhook) and this build fails with the error:

```
Extension error:
Could not import extension hoverxref.extension (exception: No module named 'hoverxref')
```
Are we missing some configuration in readthedocs? The readthedocs failed build log is attached below:
[Build log.txt](https://github.com/readthedocs/sphinx-hoverxref/files/4707396/Build.log.txt)

[This](https://github.com/Senetas/SureDrop) is our project in GitHub. To pass the build in readthedocs, we have temporarily commented out this extension in our conf.py file.

**Comment by humitos** [comment]
Hi @devamchakrabarty! You need to tell Read the Docs to install the dependencies. You can read more about this at https://docs.readthedocs.io/en/stable/guides/specifying-dependencies.html

**Comment by devamchakrabarty** [comment]
Hi @humitos , thanks for your response. We have tried defining `sphinx-hoverxref` in a [requirements.txt](https://github.com/Senetas/SureDrop/blob/master/docs/source/requirements.txt) file but landed up with the same issue. Our local builds are fine but readthedocs build are still failing if we uncomment `'hoverxref.extension'` in our [conf.py](https://github.com/Senetas/SureDrop/blob/master/docs/source/conf.py).

Any ideas what we might be doing wrong? The failed build log is attached below:

[Failed build log.txt](https://github.com/readthedocs/sphinx-hoverxref/files/4708574/Failed.build.log.txt)

**Comment by devamchakrabarty** [comment]
Hi @humitos ,
Thank you so much for responding and pointing us to the right direction. Adding `sphinx-hoverxref` in a `requirements.txt` file at the root directory of our project resolved this issue.
