### ISSUE TITLE
"Who is using this extension?" documentation section

### ISSUE THREAD

**Issue by humitos** [readthedocs/sphinx-hoverxref#88]
Consider adding a documentation page mentioning people using this extension:

* Scrapy: https://scrapy.org/doc/
* Hypothesis: https://hypothesis.readthedocs.io/
* returns: https://returns.readthedocs.io/
* poliastro: https://docs.poliastro.space/
* etc

**Comment by astrojuanlu** [comment]
Others I saw:

- https://crest.readthedocs.io/ (2.3k GH stars)
- https://docs.tweepy.org/ (8.2k GH stars)

I reviewed all projects on GitHub using this extension (there aren't that many, only 10 pages of search results) and I found no other major projects using it.
