### ISSUE TITLE
Support sphinxcontrib-bibtex

### ISSUE THREAD

**Issue by choldgraf** [readthedocs/sphinx-hoverxref#96]
It would be quite useful if this plugin could be used to support sphinxcontrib-bibtex on top of other Sphinx references. That way you could hover over a citation, and get a read-out of the content that the citation points to.

**Comment by humitos** [comment]
Interesting. I've never used `sphinxcontrib-bibtex`, but taking a look at its documentation and how it renders the cite, I think it's possible to support it.

@choldgraf do you have an example of a project that has sphinx-hoverxref enabled and uses `sphinxcontrib-bibtex` as well?

I did a small test hitting this URL https://readthedocs.org/api/v2/embed/?project=sphinxcontrib-bibtex&url=https://sphinxcontrib-bibtex.readthedocs.io/en/latest/quickstart.html%23nel87 and I got an interesting reply

We may only need to handle this as a special case (in the parser from the server), similarly as we do with `dt` inside a `glossary`.

**Comment by choldgraf** [comment]
> do you have an example of a project that has sphinx-hoverxref enabled and uses sphinxcontrib-bibtex as well?

I can always create one if need be, but not right now :-)  right now Jupyter Book doesn't work with readthedocs, so we haven't been able to test `hoverxref` behavior in it

**Comment by humitos** [comment]
> I can always create one if need be, but not right now :-) 

Nah. Don't worry. I was asking just in case that you were already using it.

> right now Jupyter Book doesn't work with readthedocs

:cry: --I'm willing this to happen soon! :crossed_fingers: Jupyter Book has _lot of potential_!

**Comment by choldgraf** [comment]
I think it shouldn't be too much work and definitely something we'd love as well. I opened up an issue to track what kinds of things need to happen for this to be possible:

https://github.com/executablebooks/jupyter-book/issues/1091

**Comment by humitos** [comment]
The backend is updated and ready to handle the request. Now, if you run this command, you get exactly what you need to show inside the tooltip (just the citation text).

```
▶ curl --silent https://readthedocs.org/api/v2/embed/\?project\=sphinxcontrib-bibtex\&url\=https://sphinxcontrib-bibtex.readthedocs.io/en/latest/quickstart.html%23nel87 | jq ".content"
[
  "<dd><p>Edward Nelson. <em>Radically Elementary Probability Theory</em>. Princeton University Press, 1987.</p>\n</dd>"
]
```

The only work missing is on the extension itself, that should find `sphinxcontrib-bibtex` nodes and inject the hoverxref `data-` attributes to work.

**Comment by humitos** [comment]
@choldgraf Hi! I opened #149 and I hope it would be included in the next release that's going to be available in the following weeks.
